name: proyectemos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  dependency_validator: ^3.2.2

  #Firebase
  # firebase_core: ^2.14.0

  # uuid: ^3.0.5
  firebase_core: ^2.10.0
  # cloud_firestore: ^4.10.0

  # cloud_firestore: ^4.8.2
  cloud_firestore: ^4.15.4

  jumping_dot: ^0.0.6

  #Authentication
  firebase_auth: ^4.6.3
  # google_sign_in: ^6.1.4
  google_sign_in: ^6.2.1
  
  #Google icon
  font_awesome_flutter: ^10.1.0

  #State management 
  provider: 
  path_provider: ^2.0.11
  # get: ^4.6.5
  
  #Video
  youtube_player_flutter: ^8.1.1
  appinio_video_player: ^1.2.2
  video_player: ^2.7.0
  chewie: ^1.7.0
  
  #url
  url_launcher: ^6.1.14

  #ImagePicker
  image_picker: ^1.0.0
  image: ^4.0.17

  #Smooth page indicator
  smooth_page_indicator: ^1.0.0+2 

  #Splash
  flutter_native_splash: ^2.2.7

  #Launcher icon
  flutter_launcher_icons: ^0.13.1 

  file_picker: ^5.2.5  
  
  carousel_slider: ^4.2.1

  #Permissions
  permission_handler: ^11.0.0

  #Audio
  # record: ^4.4.4
  record: ^5.0.4
  simple_ripple_animation: ^0.0.3
  just_audio: ^0.9.29
  percent_indicator: ^4.2.2
  audioplayers: ^5.2.1

  #Toast 
  # fluttertoast: ^8.0.9
  fluttertoast: ^8.2.4

  #Data
  shared_preferences: ^2.0.15

  #Internacional
  intl: ^0.18.1

  #Email
  mailer: ^6.0.1
  archive: ^3.3.7

  #Card
  card_swiper: ^3.0.1

  #Responsividade
  flutter_screenutil: ^5.7.0

  #Firebase Storage
  firebase_storage: ^11.2.4
  # firebase_app_check: ^0.0.9+1
  # firebase_storage: ^11.6.5
  # firebase_app_check: ^0.2.1+13
  # mockito: ^5.4.0

flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "#ffffff" #white color
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "assets/images/icon-android.png"
  lints: ^2.1.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  mockito:
  build_runner:
  lints: ^2.0.1
  
  #Lint
  flutterando_analysis: ^0.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/proyecto2.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 400
